apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: tripinsight
  labels:
    app.kubernetes.io/name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: poi
        version: beta-0514-1915
        deploy: 21-05-14-19-15-24
   
    spec:
      containers:
        - name: poi
          image: registryhhm0245.azurecr.io/poi:latest
          imagePullPolicy: Always        
          
          args: 
          - --SQL_USER
          - sqladminhHm0245
          - --SQL_PASSWORD 
          - uL6nj2Qo1 
          - --SQL_SERVER 
          - sqlserverhhm0245.database.windows.net


          ports:
            - containerPort: 80
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: tripinsight
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: poi-http
  selector:
    app: poi

